# Generated by Django 5.0.4 on 2024-05-01 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalappointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('finished', 'finished'), ('cancelled', 'Cancelled'), ('started', 'Started')], max_length=10),
        ),
    ]
