# Generated by Django 5.0.4 on 2024-06-06 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_alter_medicalappointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalappointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('finished', 'Finished'), ('cancelled', 'Cancelled'), ('started', 'Started')], max_length=10),
        ),
    ]
