# Generated by Django 5.0.4 on 2024-04-21 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('document', models.FileField(upload_to='documents')),
                ('medical_appointment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='patient.medicalappointment')),
            ],
        ),
    ]
