# Generated by Django 5.0.4 on 2024-04-24 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_document'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DoctorData',
            new_name='Doctor',
        ),
        migrations.RemoveField(
            model_name='opendate',
            name='user',
        ),
        migrations.AddField(
            model_name='opendate',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='doctor.doctor'),
            preserve_default=False,
        ),
    ]
